type: "transformation"
version: "1.0"
pipeline:
  components:
    User_Data_Input:
      type: "table-input"
      parameters:
        componentName: "User_Data_Input"
        database: "DEV_DB"
        schema: "DEV_SCHEMA"
        targetTable: "User_data"
        columnNames:
        - "UserID"
        - "UserName"
        - "Country"
        timeOffset:
    Posts_Data_Input:
      type: "table-input"
      parameters:
        componentName: "Posts_Data_Input"
        database: "DEV_DB"
        schema: "DEV_SCHEMA"
        targetTable: "Posts_Data"
        columnNames:
        - "Likes"
        - "PostID"
        - "PostTitle"
        - "RowId"
        - "UserID"
        timeOffset:
    Convert Type:
      type: "convert-type"
      sources:
      - "Posts_Data_Input"
      parameters:
        componentName: "Convert Type"
        conversions:
        - - "Likes"
          - "NUMBER"
          - ""
          - ""
        - - "UserID"
          - "NUMBER"
          - ""
          - ""
    Join:
      type: "join"
      sources:
      - "Convert Type"
      - "User_Data_Input"
      parameters:
        componentName: "Join"
        mainTable: "Convert Type"
        mainTableAlias: "Post"
        joins:
        - - "User_Data_Input"
          - "user"
          - "Inner"
        joinExpressions:
        - - "\"Post\".\"UserID\"=\"user\".\"UserID\""
          - "Post_Inner_user"
        columnMappings:
        - - "Post.Likes"
          - "Likes"
        - - "Post.PostTitle"
          - "Post_Title"
        - - "user.Country"
          - "Country"
        - - "user.UserName"
          - "User_Name"
    Rewrite Table:
      type: "rewrite-table"
      sources:
      - "Join"
      parameters:
        componentName: "Rewrite Table"
        warehouse: "COMPUTE_WH"
        database: "DEV_DB"
        schema: "DEV_SCHEMA"
        targetTable: "Table_Output"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    User_Data_Input:
      position:
        x: -320
        "y": -80
      tempMetlId: 1
    Posts_Data_Input:
      position:
        x: -320
        "y": 60
      tempMetlId: 2
    Convert Type:
      position:
        x: -130
        "y": 60
      tempMetlId: 3
    Join:
      position:
        x: -10
        "y": -30
      tempMetlId: 4
    Rewrite Table:
      position:
        x: 170
        "y": -30
      tempMetlId: 5
